# -*- coding: utf-8 -*-
"""Decorder_fn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQ6EBTQx0RFJ8510o-R7L8gOTpshPJ9w
"""





def another_function(func):
    """
    A function that accepts another function
    """

    def other_func():
        val = "The result of %s is %s" % (func(),
                                          eval(func())
                                          )
        return val
    return other_func

@another_function
def a_function():
    """A pretty useless function"""
    return "1+1"
@another_function
def b_function():
  return "2+2"

value_1 = a_function()
value_2=b_function()
print(value_1)
print(value_2)

def sum_2(func):
  def sum_3():
    x="this is from sum_3===>%s"%(func())
    return x
  return sum_3
@sum_2
def sum_1():
  return 1+1
x=sum_1()
print(x)

